// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    About: typeof import('./src/components/Info/About.vue')['default']
    Const: typeof import('./src/components/Config/Const/Const.vue')['default']
    ConstEdit: typeof import('./src/components/Config/Const/ConstEdit.vue')['default']
    ConstGroup: typeof import('./src/components/Config/ConstGroup/ConstGroup.vue')['default']
    ConstGroupEdit: typeof import('./src/components/Config/ConstGroup/ConstGroupEdit.vue')['default']
    DeleteDialog: typeof import('./src/components/Base/Dialog/DeleteDialog.vue')['default']
    EditDialog: typeof import('./src/components/Base/Dialog/EditDialog.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElMenuItemGroup: typeof import('element-plus/es')['ElMenuItemGroup']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPageHeader: typeof import('element-plus/es')['ElPageHeader']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    Header: typeof import('./src/components/Base/Header.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Loading: typeof import('./src/components/Base/Loading.vue')['default']
    Menu: typeof import('./src/components/Base/Menu.vue')['default']
    Param: typeof import('./src/components/Config/Param/Param.vue')['default']
    ParamGroup: typeof import('./src/components/Config/ParamGroup/ParamGroup.vue')['default']
    Route: typeof import('./src/components/Info/Route.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Table: typeof import('./src/components/Base/Table.vue')['default']
    Title: typeof import('./src/components/Base/Title.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
